#!/usr/bin/env bash

#MISE description="Run the tests for Dainty"

echo "🚀 Starting Dainty tests..."
proj_dir=$(git rev-parse --show-toplevel)
cd "$proj_dir" || exit 1

set -euo pipefail

NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
export NODE_EXTRA_CA_CERTS
export DATABASE_URL=$TEST_DATABASE_URL
sqlx db reset -y

cargo nextest run --all-features
bun run test
